// apps/blockprotocol-poc/libs/block-frameworks/svelte/examples/task-block.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import { createBlock, useEntity, useEntityUpdater } from '../../src/index'

  // Props from Block Protocol
  export let graph: {
    blockEntity: {
      entityId: string
      properties: Record<string, unknown>
    }
    readonly: boolean
  }

  const dispatch = createEventDispatcher()

  // Reactive entity data
  const entity = useEntity(graph)
  const updateEntity = useEntityUpdater(graph)

  // Local reactive state
  let title = $entity?.properties?.title as string || ''
  let description = $entity?.properties?.description as string || ''
  let status = $entity?.properties?.status as string || 'todo'

  // Status options
  const statusOptions = [
    { value: 'todo', label: 'To Do' },
    { value: 'in-progress', label: 'In Progress' },
    { value: 'done', label: 'Done' }
  ]

  // Update entity when local values change
  function handleUpdate() {
    updateEntity({
      title,
      description,
      status,
      lastUpdated: new Date().toISOString()
    })
  }

  // React to entity changes
  $: if ($entity?.properties?.title !== title) {
    title = $entity?.properties?.title as string || ''
  }
  $: if ($entity?.properties?.description !== description) {
    description = $entity?.properties?.description as string || ''
  }
  $: if ($entity?.properties?.status !== status) {
    status = $entity?.properties?.status as string || 'todo'
  }
</script>

<div class="task-block">
  <h3>Task Block (Svelte)</h3>

  <label class="block-field">
    <span class="block-field__label">Title:</span>
    <input
      type="text"
      bind:value={title}
      placeholder="Enter task title..."
      class="block-input"
      disabled={graph.readonly}
    />
  </label>

  <label class="block-field">
    <span class="block-field__label">Description:</span>
    <input
      type="text"
      bind:value={description}
      placeholder="Enter task description..."
      class="block-input"
      disabled={graph.readonly}
    />
  </label>

  <label class="block-field">
    <span class="block-field__label">Status:</span>
    <select
      bind:value={status}
      class="block-select"
      disabled={graph.readonly}
    >
      {#each statusOptions as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  </label>

  <button
    class="block-button block-button--primary"
    disabled={graph.readonly}
    on:click={handleUpdate}
  >
    Update Task
  </button>

  <div class="task-info">
    <small>Entity ID: {$entity?.entityId || 'none'}</small>
  </div>
</div>

<style>
  .task-block {
    background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%);
    color: white;
    padding: 1.5rem;
    border-radius: 12px;
  }

  .block-field {
    display: flex;
    flex-direction: column;
    margin-bottom: 1rem;
  }

  .block-field__label {
    margin-bottom: 0.5rem;
    font-weight: 600;
  }

  .block-input,
  .block-select {
    padding: 0.5rem;
    border: 1px solid rgba(255, 255, 255, 0.3);
    border-radius: 4px;
    background: rgba(255, 255, 255, 0.1);
    color: white;
  }

  .block-input::placeholder {
    color: rgba(255, 255, 255, 0.6);
  }

  .block-button {
    align-self: flex-start;
    padding: 0.5rem 1rem;
    border: none;
    border-radius: 4px;
    background: rgba(255, 255, 255, 0.2);
    color: white;
    font-weight: 600;
    cursor: pointer;
    transition: background 0.2s;
  }

  .block-button:hover:not(:disabled) {
    background: rgba(255, 255, 255, 0.3);
  }

  .block-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .task-info {
    margin-top: 1rem;
    opacity: 0.8;
  }
</style>

// packages/block-frameworks/solidjs/examples/task-block.tsx
// Standalone SolidJS Block Protocol implementation
import { createSignal, createElement, Fragment } from 'solid-js'

// Block Protocol types (standalone)
interface Entity {
  entityId: string
  entityTypeId: string
  properties: Record<string, unknown>
}

interface BlockGraph {
  depth: number
  linkedEntities: Entity[]
  linkGroups: Array<Record<string, unknown>>
}

interface GraphService {
  blockEntity: Entity
  blockGraph: BlockGraph
  entityTypes: Array<Record<string, unknown>>
  linkedAggregations: Array<Record<string, unknown>>
  readonly: boolean
  updateEntity?(updates: Partial<Entity['properties']>): void
}

interface BlockProps {
  graph: GraphService
}

// SolidJS Block Protocol helper (standalone)
function createBlockElement(
  component: (props: BlockProps) => any,
  options: {
    name: string
    version?: string
    description?: string
  }
) {
  return {
    component,
    metadata: options
  }
}

// Simple components (standalone)
const BlockContainer = (props: { children: any }) => (
  <div style={{
    "border": "2px solid #8b5cf6",
    "border-radius": "8px",
    "padding": "1rem",
    "background": "rgba(139, 92, 246, 0.08)",
    "font-family": "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
  }}>
    {props.children}
  </div>
)

const BlockField = (props: { label: string, children: any }) => (
  <label style={{
    "display": "flex",
    "flex-direction": "column",
    "margin-bottom": "0.5rem"
  }}>
    <span style={{
      "margin-bottom": "0.25rem",
      "font-weight": "600",
      "color": "#374151"
    }}>
      {props.label}
    </span>
    {props.children}
  </label>
)

const BlockInput = (props: {
  value: string
  onChange: (value: string) => void
  placeholder?: string
}) => (
  <input
    type="text"
    value={props.value}
    placeholder={props.placeholder || ''}
    onInput={(e) => props.onChange((e.target as HTMLInputElement).value)}
    style={{
      "padding": "0.4rem 0.5rem",
      "border": "1px solid #ddd6fe",
      "border-radius": "4px",
      "font-size": "0.95rem",
      "background": "white"
    }}
  />
)

const BlockButton = (props: { onClick: () => void, children: any }) => (
  <button
    onClick={props.onClick}
    style={{
      "align-self": "flex-start",
      "padding": "0.4rem 0.8rem",
      "border-radius": "4px",
      "border": "none",
      "background": "#8b5cf6",
      "color": "white",
      "font-weight": "600",
      "cursor": "pointer"
    }}
  >
    {props.children}
  </button>
)

// Example task block using standalone SolidJS implementation
const TaskBlock = createBlockElement((props) => {
  const [title, setTitle] = createSignal('')
  const [description, setDescription] = createSignal('')
  const [status, setStatus] = createSignal('todo')

  const updateTask = () => {
    if (props.graph?.updateEntity) {
      props.graph.updateEntity({
        title: title(),
        description: description(),
        status: status()
      })
    }
  }

  return (
    <BlockContainer>
      <h3 style={{ "margin": "0 0 0.5rem 0", "font-size": "1.1rem", "color": "#5b21b6" }}>
        SolidJS Task Block
      </h3>
      <BlockField label="Title">
        <BlockInput
          value={title()}
          onChange={setTitle}
          placeholder="Enter task title..."
        />
      </BlockField>
      <BlockField label="Description">
        <BlockInput
          value={description()}
          onChange={setDescription}
          placeholder="Enter task description..."
        />
      </BlockField>
      <BlockField label="Status">
        <select
          value={status()}
          onChange={(e) => setStatus((e.target as HTMLSelectElement).value)}
          style={{
            "padding": "0.4rem 0.5rem",
            "border": "1px solid #ddd6fe",
            "border-radius": "4px",
            "font-size": "0.95rem",
            "background": "white"
          }}
        >
          <option value="todo">To Do</option>
          <option value="in-progress">In Progress</option>
          <option value="done">Done</option>
        </select>
      </BlockField>
      <BlockButton onClick={updateTask}>
        Update Task
      </BlockButton>
      <div style={{ "font-size": "0.8rem", "color": "#5b21b6", "margin-top": "0.5rem" }}>
        Entity ID: {props.graph?.blockEntity?.entityId || 'N/A'} | Framework: SolidJS
      </div>
    </BlockContainer>
  )
}, {
  name: 'solidjs-task-block',
  version: '0.1.0',
  description: 'A task management block built with SolidJS'
})

export default TaskBlock
