// packages/block-frameworks/solidjs/src/index.tsx
import { Component, createSignal, JSX, onMount, onCleanup } from 'solid-js'
import { render } from 'solid-js/web'
// Reuse shared core types: import for local use and re-export for consumers
import type { Entity, BlockGraph, GraphService, BlockProps } from '@vivafolio/block-core'
export type { Entity, BlockGraph, GraphService, BlockProps } from '@vivafolio/block-core'

// Web Component wrapper type (supports custom graph types)
export type BlockComponent<TProps extends Record<string, any> = BlockProps> = Component<TProps>

// Helper to create a Block Protocol compatible SolidJS component
export function createSolidBlock<T extends Record<string, any> = {}>(
  component: BlockComponent<BlockProps & T>,
  options: {
    name: string
    version?: string
    description?: string
  }
): {
  (props: BlockProps & T): JSX.Element
  blockMetadata: typeof options
} {
  const wrappedComponent = (props: BlockProps & T) => {
    return component(props)
  }
  ;(wrappedComponent as any).blockMetadata = options
  return wrappedComponent as any
}

// Hook for accessing entity data with reactivity (supports any GraphService type)
export function useEntity<TGraph extends { blockEntity: Entity }>(graph: TGraph) {
  const [entity, setEntity] = createSignal(graph.blockEntity)

  // In a real implementation, this would listen to graph updates
  // For now, we'll just return the initial entity
  return entity
}

// Hook for updating entity properties
export function useEntityUpdater<TGraph extends { blockEntity: Entity }>(graph: TGraph) {
  return (updates: Partial<Entity['properties']>) => {
    // In a real implementation, this would call the Block Protocol updateEntity method
    console.log('Entity update requested:', updates)
  }
}

// Base block wrapper styles (CSS-in-JS for SolidJS)
export const blockStyles = `
  .solidjs-block-container {
    display: block;
    border: 2px solid #8b5cf6;
    border-radius: 8px;
    padding: 1rem;
    background: rgba(139, 92, 246, 0.08);
    font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  }

  .solidjs-block-heading {
    margin: 0 0 0.5rem 0;
    font-size: 1.1rem;
    color: #5b21b6;
  }

  .solidjs-block-body {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .solidjs-block-field {
    display: flex;
    flex-direction: column;
    font-size: 0.9rem;
    color: #374151;
  }

  .solidjs-block-field__label {
    margin-bottom: 0.25rem;
    font-weight: 600;
  }

  .solidjs-block-input,
  .solidjs-block-select {
    padding: 0.4rem 0.5rem;
    border: 1px solid #ddd6fe;
    border-radius: 4px;
    font-size: 0.95rem;
    background: white;
  }

  .solidjs-block-input:disabled,
  .solidjs-block-select:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .solidjs-block-button {
    align-self: flex-start;
    padding: 0.4rem 0.8rem;
    border-radius: 4px;
    border: none;
    background: #8b5cf6;
    color: white;
    font-weight: 600;
    cursor: pointer;
  }

  .solidjs-block-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .solidjs-block-button:hover:not(:disabled) {
    background: #7c3aed;
  }

  .solidjs-block-footnote {
    font-size: 0.8rem;
    color: #5b21b6;
    margin-top: 0.5rem;
  }
`

// Form field components for common block patterns
export const BlockContainer: Component<{
  className?: string
  children: any
}> = (props) => {
  onMount(() => {
    // Inject styles if not already present
    if (!document.querySelector('#solidjs-block-styles')) {
      const style = document.createElement('style')
      style.id = 'solidjs-block-styles'
      style.textContent = blockStyles
      document.head.appendChild(style)
    }
  })

  return (
    <div class={`solidjs-block-container ${props.className || ''}`}>
      {props.children}
    </div>
  )
}

export const BlockField: Component<{
  label: string
  children: any
}> = (props) => {
  return (
    <label class="solidjs-block-field">
      <span class="solidjs-block-field__label">{props.label}</span>
      {props.children}
    </label>
  )
}

export const BlockInput: Component<{
  value: string
  onChange: (value: string) => void
  placeholder?: string
  disabled?: boolean
  type?: 'text' | 'email' | 'url' | 'number'
}> = (props) => {
  return (
    <input
      type={props.type || 'text'}
      value={props.value}
      placeholder={props.placeholder || ''}
      disabled={props.disabled}
      class="solidjs-block-input"
      onInput={(e) => props.onChange((e.target as HTMLInputElement).value)}
    />
  )
}

export const BlockSelect: Component<{
  value: string
  options: Array<{ value: string; label: string }>
  onChange: (value: string) => void
  disabled?: boolean
}> = (props) => {
  return (
    <select
      value={props.value}
      disabled={props.disabled}
      class="solidjs-block-select"
      onChange={(e) => props.onChange((e.target as HTMLSelectElement).value)}
    >
      {props.options.map(option => (
        <option value={option.value}>{option.label}</option>
      ))}
    </select>
  )
}

export const BlockButton: Component<{
  onClick: () => void
  children: any
  disabled?: boolean
}> = (props) => {
  return (
    <button
      class="solidjs-block-button"
      disabled={props.disabled}
      onClick={props.onClick}
    >
      {props.children}
    </button>
  )
}

// Enhanced factory function that supports custom GraphService interfaces
export function createBlockElement<TGraph extends Partial<GraphService> = GraphService>(
  component: Component<BlockProps<TGraph>>,
  options: {
    name: string
    version?: string
    description?: string
  }
): {
  element: typeof HTMLElement
  init: (params: {
    element: HTMLElement
    graph: TGraph
  }) => (() => void)
  updateGraph: (params: {
    element: HTMLElement
    graph: TGraph
  }) => void
} {
  class SolidBlockElement extends HTMLElement {
    public graph?: TGraph
    public _dispose?: () => void
    public _setGraph?: (g: TGraph) => void
    constructor() { super() }
    connectedCallback() {
      if (this.graph && !this._dispose) {
        const cleanup = init({ element: this, graph: this.graph })
        this._dispose = cleanup
      }
    }
    disconnectedCallback() {
      if (this._dispose) { this._dispose(); this._dispose = undefined; this._setGraph = undefined }
    }
  }

  const init = (params: { element: HTMLElement; graph: TGraph }): (() => void) => {
    const { element, graph } = params
    const blockElement = element as SolidBlockElement
    let container = element.querySelector(':scope > .solidjs-root') as HTMLDivElement | null
    if (!container) {
      container = document.createElement('div')
      container.className = 'solidjs-root'
      container.style.width = '100%'
      container.style.height = '100%'
      element.appendChild(container)
    }
    const [graphSignal, setGraphSignal] = createSignal<TGraph>(graph)
    blockElement.graph = graph
    blockElement._setGraph = setGraphSignal
    const dispose = render(() => component({ graph: graphSignal() } as BlockProps<TGraph>), container)
    const cleanup = () => { dispose(); blockElement._setGraph = undefined }
    blockElement._dispose = cleanup

    // Inject block styles if not already present
    if (!document.querySelector('#solidjs-block-styles')) {
      const style = document.createElement('style')
      style.id = 'solidjs-block-styles'
      style.textContent = blockStyles
      document.head.appendChild(style)
    }

    // Return cleanup function
    return cleanup
  }

  const updateGraph = (params: { element: HTMLElement; graph: TGraph }) => {
    const blockElement = params.element as SolidBlockElement
    if (!blockElement._dispose) { init(params); return }
    blockElement.graph = params.graph
    blockElement._setGraph?.(params.graph)
  }

  return {
    element: SolidBlockElement,
    init,
    updateGraph
  }
}



// Utility function to register a SolidJS component as a Web Component
export function registerBlockElement(
  tagName: string,
  solidComponent: Component<any>,
  propsMapper?: (element: HTMLElement) => Record<string, unknown>
) {
  // SolidJS components are registered via the createBlockElement factory
  console.log(`SolidJS component registered as ${tagName}`)
}

// packages/block-frameworks/lit/src/index.ts
import { LitElement, html, css, type TemplateResult, type CSSResult } from 'lit'
import { property } from 'lit/decorators.js'
import { customElement } from 'lit/decorators.js'

// Reuse shared core types: import for local use and re-export for consumers
import type { Entity, BlockGraph, GraphService, BlockProps } from '@vivafolio/block-core'
export type { Entity, BlockGraph, GraphService, BlockProps } from '@vivafolio/block-core'

type EntityProperties = NonNullable<Entity['properties']>

// Lit component base class
export abstract class BlockElement extends LitElement {
  @property({ type: Object })
  graph!: GraphService

  // Reactive entity data
  protected get entity(): Entity {
    return this.graph?.blockEntity || {} as Entity
  }

  protected get readonly(): boolean {
    return this.graph?.readonly || false
  }

  // Helper method for updating entity properties
  protected updateEntity(updates: Partial<EntityProperties>) {
    // In a real implementation, this would call the Block Protocol updateEntity method
    console.log('Entity update requested:', updates)
    this.dispatchEvent(new CustomEvent('entity-update', {
      detail: updates,
      bubbles: true,
      composed: true
    }))
  }
}

// Helper to create a Block Protocol compatible Lit component
export function createBlock<T extends BlockElement>(
  componentClass: new () => T,
  options: {
    name: string
    version?: string
    description?: string
  }
): new () => T {
  // Apply metadata to the class
  ;(componentClass as any).blockMetadata = options
  return componentClass
}

// Base block wrapper styles
export const blockStyles = css`
  :host {
    display: block;
    border: 2px solid #10b981;
    border-radius: 8px;
    padding: 1rem;
    background: rgba(16, 185, 129, 0.08);
    font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  }

  .block-heading {
    margin: 0 0 0.5rem 0;
    font-size: 1.1rem;
    color: #065f46;
  }

  .block-body {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .block-field {
    display: flex;
    flex-direction: column;
    font-size: 0.9rem;
    color: #14532d;
  }

  .block-field__label {
    margin-bottom: 0.25rem;
    font-weight: 600;
  }

  .block-input,
  .block-select {
    padding: 0.4rem 0.5rem;
    border: 1px solid #bbf7d0;
    border-radius: 4px;
    font-size: 0.95rem;
    background: white;
  }

  .block-input:disabled,
  .block-select:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .block-button {
    align-self: flex-start;
    padding: 0.4rem 0.8rem;
    border-radius: 4px;
    border: none;
    background: #10b981;
    color: white;
    font-weight: 600;
    cursor: pointer;
  }

  .block-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .block-button:hover:not(:disabled) {
    background: #059669;
  }

  .block-footnote {
    font-size: 0.8rem;
    color: #065f46;
    margin-top: 0.5rem;
  }
`

// Form field components for common block patterns
export const BlockField = (label: string, content: TemplateResult) => html`
  <label class="block-field">
    <span class="block-field__label">${label}</span>
    ${content}
  </label>
`

export const BlockInput = (
  value: string,
  onInput: (value: string) => void,
  options: {
    placeholder?: string
    disabled?: boolean
    type?: 'text' | 'email' | 'url' | 'number'
  } = {}
) => html`
  <input
    type=${options.type || 'text'}
    .value=${value}
    placeholder=${options.placeholder || ''}
    ?disabled=${options.disabled}
    class="block-input"
    @input=${(e: Event) => onInput((e.target as HTMLInputElement).value)}
  />
`

export const BlockSelect = (
  value: string,
  options: Array<{ value: string; label: string }>,
  onChange: (value: string) => void,
  disabled: boolean = false
) => html`
  <select
    .value=${value}
    ?disabled=${disabled}
    class="block-select"
    @change=${(e: Event) => onChange((e.target as HTMLSelectElement).value)}
  >
    ${options.map(option => html`
      <option value=${option.value}>${option.label}</option>
    `)}
  </select>
`

export const BlockButton = (
  onClick: () => void,
  content: TemplateResult,
  options: {
    disabled?: boolean
    variant?: 'primary' | 'secondary' | 'danger'
  } = {}
) => html`
  <button
    class="block-button block-button--${options.variant || 'primary'}"
    ?disabled=${options.disabled}
    @click=${onClick}
  >
    ${content}
  </button>
`

// Utility function to register a Lit component as a Web Component
export function registerBlockElement(
  tagName: string,
  litComponent: new () => LitElement,
  propsMapper?: (element: HTMLElement) => Record<string, unknown>
) {
  // Lit components are automatically registered as custom elements
  // when using the @customElement decorator
  console.log(`Lit component registered as ${tagName}`)
}
